export type Book = {
    _id?: string; // Optional, as it will be generated by MongoDB
    title: string;
    author: string;
    genre: string[];
    url_image: string;
    isbn?: string; // Optional field for ISBN number
};
